
trigger: none

variables:
- template: ./config.yml

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
      - task: UseDotNet@2
        inputs:
          packageType: "sdk"
          version: "6.0.x"
      
      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: "restore"
          projects: "src/ContosoUniversity.sln"
      
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: "build"
          projects: "src/ContosoUniversity.sln"
          arguments: "--configuration $(CONFIGURATION) --no-restore"
      
      # - task: DotNetCoreCLI@6
      #   displayName: "Test"
      #   inputs:
      #     command: "test"
      #     projects: "src/ContosoUniversity.Test/ContosoUniversity.Test.csproj"
      #     arguments: "--verbosity normal --logger trx --results-directory TestResults"
      
      - task: DotNetCoreCLI@2
        displayName: "Publish APP"
        inputs:
          command: "publish"
          arguments: "--configuration $(CONFIGURATION) --output PublishApp"
          projects: "src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj"
      
      - task: DotNetCoreCLI@2
        displayName: "Publish API"
        inputs:
          command: "publish"
          arguments: "--configuration $(CONFIGURATION) --output PublishApi"
          projects: "src/ContosoUniversity.API/ContosoUniversity.API.csproj"
      
      - task: PublishPipelineArtifact@1
        displayName: "Upload APP results"
        inputs:
          artifactName: "app"
          path: "PublishApp"
      
      - task: PublishPipelineArtifact@1
        displayName: "Upload API results"
        inputs:
          artifactName: "api"
          path: "PublishApi"

  - job: Release
    dependsOn: build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: "Dowload Pipeline App Artifact" 
        inputs:
          artifact: "app"
          path: "$(System.ArtifactsDirectory)/app-artifact"

      - task: DownloadPipelineArtifact@2
        displayName: "Dowload Pipeline API Artifact"
        inputs:
          artifact: "api"
          path: "$(System.ArtifactsDirectory)/api-artifact"

      - task: AzureRmWebAppDeployment@4
        displayName: "Web App Deployment"
        inputs:
          ConnectionType: "AzureRM"
          azureSubscription: sp-luketaylor-dev
          appType: "webApp"
          WebAppName: $(api_name)
          packageForLinux: "$(System.ArtifactsDirectory)/api-artifact/ContosoUniversity.API.zip"
          JSONFiles: '**/appsettings.json'

      - task: AzureRmWebAppDeployment@4
        displayName: "Web API Deployment"
        inputs:
          ConnectionType: "AzureRM"
          azureSubscription: sp-luketaylor-dev
          appType: "webApp"
          WebAppName: $(app_name)
          packageForLinux: "$(System.ArtifactsDirectory)/app-artifact/ContosoUniversity.WebApplication.zip"
          JSONFiles: '**/appsettings.json'

